# struct HydroUnit
#     name::String
#     StartArc::Vector{Int32}
#     EndArc::Vector{Int32}
#     Inflows::Matrix{Float64}
#     InitialVolumetric::Vector{Float64}
#     MinVolumetric::Matrix{Float64}
#     MaxVolumetric::Matrix{Float64}
#     UphillFlow::Vector{Int32}
#     DownhillFlow::Vector{Int32}
#     InitialFlowRate::Vector{Int32}
#     DeltaRampUp::Matrix{Float64}
#     DeltaRampDown::Matrix{Float64}
#     MinFlow::Matrix{Float64}
#     MaxFlow::Matrix{Float64}
#     MinPower::Matrix{Float64}
#     MaxPower::Matrix{Float64}
#     NumberPieces::Vector{Int32}
#     LinearTerm::Vector{Float64}
#     ConstantTerm::Vector{Float64}
# end